on: [push, pull_request]

name: Test

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -race -covermode atomic -coverprofile=covprofile ./...
    - name: Install goveralls
      run: go get github.com/mattn/goveralls
    - name: Send coverage
      run: goveralls -coverprofile=covprofile -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}